import smtplib
import ssl
import aiohttp
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Optional, TYPE_CHECKING
import logging
from dataclasses import dataclass

if TYPE_CHECKING:
    from alerts import Alert, AlertSeverity

logger = logging.getLogger(__name__)

@dataclass
class EmailConfig:
    smtp_server: str
    smtp_port: int
    username: str
    password: str
    sender_email: str
    recipient_emails: List[str]
    use_tls: bool = True

class EmailNotifier:
    """邮件通知器"""
    def __init__(self, config: Optional[EmailConfig] = None):
        self.config = config
        self.enabled = config is not None

    def set_config(self, config: EmailConfig):
        """设置邮件配置"""
        self.config = config
        self.enabled = True

    def send_alert_email(self, alert: 'Alert') -> bool:
        """发送告警邮件"""
        if not self.enabled or not self.config:
            logger.warning("Email notifier is not configured or disabled")
            return False

        try:
            # 创建邮件
            message = MIMEMultipart("alternative")
            message["Subject"] = f"[{alert.severity.value.upper()}] Server Alert: {alert.message[:50]}..."
            message["From"] = self.config.sender_email
            message["To"] = ", ".join(self.config.recipient_emails)

            # 创建邮件正文
            text_body = self._create_text_body(alert)
            html_body = self._create_html_body(alert)

            # 添加文本和HTML部分
            part1 = MIMEText(text_body, "plain")
            part2 = MIMEText(html_body, "html")
            message.attach(part1)
            message.attach(part2)

            # 发送邮件
            context = ssl.create_default_context()
            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                if self.config.use_tls:
                    server.starttls(context=context)
                server.login(self.config.username, self.config.password)
                server.sendmail(self.config.sender_email, self.config.recipient_emails, message.as_string())

            logger.info(f"Alert email sent successfully for alert {alert.id}")
            return True

        except Exception as e:
            logger.error(f"Failed to send alert email: {e}")
            return False

    def _create_text_body(self, alert: 'Alert') -> str:
        """创建文本格式的邮件正文"""
        body = f"""
Server Alert Notification

Server: {alert.server_name}
Alert Type: {alert.alert_type.value}
Severity: {alert.severity.value.upper()}
Message: {alert.message}
Current Value: {alert.current_value}
Threshold: {alert.threshold_value}
Timestamp: {alert.timestamp}

This is an automated message from the Server Monitor system.
        """
        return body.strip()

    def _create_html_body(self, alert: 'Alert') -> str:
        """创建HTML格式的邮件正文"""
        # 根据告警严重程度设置颜色
        from alerts import AlertSeverity
        severity_colors = {
            AlertSeverity.LOW: "#28a745",      # 绿色
            AlertSeverity.MEDIUM: "#ffc107",   # 黄色
            AlertSeverity.HIGH: "#fd7e14",     # 橙色
            AlertSeverity.CRITICAL: "#dc3545"  # 红色
        }

        color = severity_colors.get(alert.severity, "#007bff")

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; }}
                .header {{ background-color: {color}; color: white; padding: 10px; }}
                .content {{ padding: 20px; }}
                .alert-info {{ background-color: #f8f9fa; padding: 15px; border-left: 5px solid {color}; margin: 15px 0; }}
                .footer {{ font-size: 12px; color: #6c757d; margin-top: 20px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>Server Alert Notification</h2>
            </div>
            <div class="content">
                <div class="alert-info">
                    <h3>Alert Details</h3>
                    <p><strong>Server:</strong> {alert.server_name}</p>
                    <p><strong>Alert Type:</strong> {alert.alert_type.value.replace('_', ' ').title()}</p>
                    <p><strong>Severity:</strong> <span style="color: {color}; font-weight: bold;">{alert.severity.value.upper()}</span></p>
                    <p><strong>Message:</strong> {alert.message}</p>
                    <p><strong>Current Value:</strong> {alert.current_value}</p>
                    <p><strong>Threshold:</strong> {alert.threshold_value}</p>
                    <p><strong>Timestamp:</strong> {alert.timestamp}</p>
                </div>
                <p>This is an automated message from the Server Monitor system.</p>
            </div>
            <div class="footer">
                <p>Generated by Remote Server Monitor</p>
            </div>
        </body>
        </html>
        """
        return html

    def test_connection(self) -> bool:
        """测试邮件服务器连接"""
        if not self.config:
            return False

        try:
            context = ssl.create_default_context()
            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                if self.config.use_tls:
                    server.starttls(context=context)
                server.login(self.config.username, self.config.password)
            return True
        except Exception as e:
            logger.error(f"Failed to test email connection: {e}")
            return False

@dataclass
class WebhookConfig:
    url: str
    headers: Optional[dict] = None
    enabled: bool = True
    timeout: int = 30  # 请求超时时间（秒）

class WebhookNotifier:
    """Webhook通知器"""
    def __init__(self, config: Optional[WebhookConfig] = None):
        self.config = config
        self.enabled = config is not None

    def set_config(self, config: WebhookConfig):
        """设置Webhook配置"""
        self.config = config
        self.enabled = True

    async def send_alert_webhook(self, alert: 'Alert') -> bool:
        """发送告警Webhook"""
        if not self.enabled or not self.config:
            logger.warning("Webhook notifier is not configured or disabled")
            return False

        try:
            # 创建Webhook负载
            payload = {
                "event": "server_alert",
                "alert_id": alert.id,
                "server_name": alert.server_name,
                "alert_type": alert.alert_type.value,
                "severity": alert.severity.value,
                "message": alert.message,
                "current_value": alert.current_value,
                "threshold_value": alert.threshold_value,
                "timestamp": alert.timestamp.isoformat() if hasattr(alert.timestamp, 'isoformat') else str(alert.timestamp),
                "acknowledged": alert.acknowledged
            }

            # 设置请求头
            headers = self.config.headers or {}
            headers['Content-Type'] = 'application/json'

            # 发送Webhook请求
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    self.config.url,
                    json=payload,
                    headers=headers,
                    timeout=aiohttp.ClientTimeout(total=self.config.timeout)
                ) as response:
                    if response.status in [200, 201, 202]:
                        logger.info(f"Alert webhook sent successfully for alert {alert.id}")
                        return True
                    else:
                        logger.error(f"Failed to send webhook: HTTP {response.status}")
                        return False

        except Exception as e:
            logger.error(f"Failed to send alert webhook: {e}")
            return False

# 全局通知器实例
email_notifier = EmailNotifier()
webhook_notifier = WebhookNotifier()

def setup_email_notifier_from_config():
    """根据配置设置邮件通知器"""
    from config import config
    email_cfg = config.monitoring.email_notifications

    if email_cfg.enabled:
        email_config = EmailConfig(
            smtp_server=email_cfg.smtp_server,
            smtp_port=email_cfg.smtp_port,
            username=email_cfg.username,
            password=email_cfg.password,
            sender_email=email_cfg.sender_email,
            recipient_emails=email_cfg.recipient_emails,
            use_tls=email_cfg.use_tls
        )
        email_notifier.set_config(email_config)
        logger.info("Email notifier configured from config")
    else:
        logger.info("Email notifications are disabled")

def setup_webhook_notifier_from_config():
    """根据配置设置Webhook通知器"""
    from config import config
    webhook_cfg = config.monitoring.webhook_notifications

    if webhook_cfg.enabled and webhook_cfg.url:
        webhook_config = WebhookConfig(
            url=webhook_cfg.url,
            headers=webhook_cfg.headers,
            enabled=webhook_cfg.enabled,
            timeout=webhook_cfg.timeout
        )
        webhook_notifier.set_config(webhook_config)
        logger.info("Webhook notifier configured from config")
    else:
        logger.info("Webhook notifications are disabled")

# 初始化通知器
setup_email_notifier_from_config()
setup_webhook_notifier_from_config()