CREATE TABLE GKBWL340R001
(
    NO                             NUMBER(38,0),
    IDO_KAISHI                     NVARCHAR2(1000),
    IDO_SHURYO                     NVARCHAR2(1000),
    SAKUSEIBI                      NVARCHAR2(1000),
    JIDO_SHIMEI_KANA               NVARCHAR2(1000),
    JIDO_SHIMEI_KANJI              NVARCHAR2(1000),
    JIDO_KOJIN_NO                  NVARCHAR2(1000),
    HOGOSHA_SHIMEI_KANA            NVARCHAR2(1000),
    HOGOSHA_SHIMEI_KANJI           NVARCHAR2(1000),
    HOGOSHA_KOJIN_NO               NVARCHAR2(1000),
    SEINENGAPI                     NVARCHAR2(1000),
    SEIBETSU                       NVARCHAR2(1000),
    HOGOSHA_KANKEI                 NVARCHAR2(1000),
    JIDO_ZOKUGARAMEI               NVARCHAR2(1000),
    SHORIBI                        NVARCHAR2(1000),
    GAKKO_MEI                      NVARCHAR2(1000),
    TENNYUGAKU_BI                  NVARCHAR2(1000),
    TENNYUGAKU_GAKUNEN             NVARCHAR2(1000),
    TENGAKU_BI                     NVARCHAR2(1000),
    TENGAKU_GAKUNEN                NVARCHAR2(1000),
    TAIGAKU_BI                     NVARCHAR2(1000),
    TAIGAKU_GAKUNEN                NVARCHAR2(1000),
    SOTSUGYO_BI                    NVARCHAR2(1000),
    YUBIN_NO                       NVARCHAR2(1000),
    JUSHO                          NVARCHAR2(1000),
    JIDO_YUBIN_NO                  NVARCHAR2(1000),
    JIDO_JUSHO                     NVARCHAR2(1000),
    SHUGAKU                        NVARCHAR2(1000),
    IDO_JIKO                       NVARCHAR2(1000),
    KAIPAGE_CD                     NVARCHAR2(1000),
    KAIPAGE_MEI                    NVARCHAR2(1000),
    JINKAKU_KBN                    NVARCHAR2(1000),
    MAE_SHIMEI_KANA                NVARCHAR2(1000),
    MAE_SHIMEI_KANJI               NVARCHAR2(1000),
    MAE_HOGOSHA_SHIMEI_KANA        NVARCHAR2(1000),
    MAE_HOGOSHA_SHIMEI_KANJI       NVARCHAR2(1000),
    MAE_SEINENGAPI                 NVARCHAR2(1000),
    MAE_SEIBETSU                   NVARCHAR2(1000),
    MAE_JIDO_KANKEI                NVARCHAR2(1000),
    MAE_JIDO_KOKUSEKI              NVARCHAR2(1000),
    MAE_HOGOSYA_KOKUSEKI           NVARCHAR2(1000),
    MAE_GAKOMEI                    NVARCHAR2(1000),
    MAE_GAKUNEN                    NVARCHAR2(1000),
    MAE_JIDOJUSHO                  NVARCHAR2(1000),
    MAE_NUSHI_SHIMEI_KANJI         NVARCHAR2(1000),
    HENKO_TODOKEDE_BI              NVARCHAR2(1000),
    HENKO_BI                       NVARCHAR2(1000),
    JIDO_KOKUSEKI                  NVARCHAR2(1000),
    HOGOSYA_KOKUSEKI               NVARCHAR2(1000),
    GAKOMEI                        NVARCHAR2(1000),
    GAKUNEN                        NVARCHAR2(1000),
    NUSHI_SHIMEI_KANJI_HENKOUGO    NVARCHAR2(1000),
    HENKO_JIYU                     NVARCHAR2(1000),
    HENKO_TODOKEDE_BI_KAISHI       NVARCHAR2(1000),
    HENKO_TODOKEDE_BI_SHURYO       NVARCHAR2(1000),
    HENKO_BI_KAISHI                NVARCHAR2(1000),
    HENKO_BI_SHURYO                NVARCHAR2(1000),
    BREAK_NO                       NVARCHAR2(1000),
    WSNUM                          NVARCHAR2(63),
    BATCHKBN                       NUMBER(2,0),
    JOBNUM                         NUMBER(38,0)
)
TABLESPACE GK_DATA
NOCACHE
LOGGING
/
COMMENT ON TABLE GKBWL340R001 IS '教育異動者一覧表'
/
COMMENT ON COLUMN GKBWL340R001.NO IS 'ソート順'
/
COMMENT ON COLUMN GKBWL340R001.IDO_KAISHI IS '抽出開始異動日'
/
COMMENT ON COLUMN GKBWL340R001.IDO_SHURYO IS '抽出終了異動日'
/
COMMENT ON COLUMN GKBWL340R001.SAKUSEIBI IS '作成日'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_SHIMEI_KANA IS '児童氏名かな'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_SHIMEI_KANJI IS '児童氏名漢字'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_KOJIN_NO IS '児童個人番号'
/
COMMENT ON COLUMN GKBWL340R001.HOGOSHA_SHIMEI_KANA IS '保護者氏名かな'
/
COMMENT ON COLUMN GKBWL340R001.HOGOSHA_SHIMEI_KANJI IS '保護者氏名漢字'
/
COMMENT ON COLUMN GKBWL340R001.HOGOSHA_KOJIN_NO IS '保護者個人番号'
/
COMMENT ON COLUMN GKBWL340R001.SEINENGAPI IS '生年月日'
/
COMMENT ON COLUMN GKBWL340R001.SEIBETSU IS '性別'
/
COMMENT ON COLUMN GKBWL340R001.HOGOSHA_KANKEI IS '保護者との関係'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_ZOKUGARAMEI IS '児童との関係'
/
COMMENT ON COLUMN GKBWL340R001.SHORIBI IS '処理年月日'
/
COMMENT ON COLUMN GKBWL340R001.GAKKO_MEI IS '学校名'
/
COMMENT ON COLUMN GKBWL340R001.TENNYUGAKU_BI IS '転入学年月日'
/
COMMENT ON COLUMN GKBWL340R001.TENNYUGAKU_GAKUNEN IS '転入学年月日学年'
/
COMMENT ON COLUMN GKBWL340R001.TENGAKU_BI IS '転学年月日'
/
COMMENT ON COLUMN GKBWL340R001.TENGAKU_GAKUNEN IS '転学年月日学年'
/
COMMENT ON COLUMN GKBWL340R001.TAIGAKU_BI IS '退学年月日'
/
COMMENT ON COLUMN GKBWL340R001.TAIGAKU_GAKUNEN IS '退学年月日学年'
/
COMMENT ON COLUMN GKBWL340R001.SOTSUGYO_BI IS '卒業年月日'
/
COMMENT ON COLUMN GKBWL340R001.YUBIN_NO IS '郵便番号'
/
COMMENT ON COLUMN GKBWL340R001.JUSHO IS '住所'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_YUBIN_NO IS '児童郵便'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_JUSHO IS '児童住所'
/
COMMENT ON COLUMN GKBWL340R001.SHUGAKU IS '就学状況'
/
COMMENT ON COLUMN GKBWL340R001.IDO_JIKO IS '異動事項'
/
COMMENT ON COLUMN GKBWL340R001.KAIPAGE_CD IS '改頁コード'
/
COMMENT ON COLUMN GKBWL340R001.KAIPAGE_MEI IS '改頁名'
/
COMMENT ON COLUMN GKBWL340R001.JINKAKU_KBN IS '人格区分'
/
COMMENT ON COLUMN GKBWL340R001.MAE_SHIMEI_KANA IS '変更前児童氏名カナ'
/
COMMENT ON COLUMN GKBWL340R001.MAE_SHIMEI_KANJI IS '変更前児童氏名漢字'
/
COMMENT ON COLUMN GKBWL340R001.MAE_HOGOSHA_SHIMEI_KANA IS '変更前保護者氏名カナ'
/
COMMENT ON COLUMN GKBWL340R001.MAE_HOGOSHA_SHIMEI_KANJI IS '変更前保護者氏名漢字'
/
COMMENT ON COLUMN GKBWL340R001.MAE_SEINENGAPI IS '変更前生年月日'
/
COMMENT ON COLUMN GKBWL340R001.MAE_SEIBETSU IS '変更前性別'
/
COMMENT ON COLUMN GKBWL340R001.MAE_JIDO_KANKEI IS '変更前児童生徒との関係'
/
COMMENT ON COLUMN GKBWL340R001.MAE_JIDO_KOKUSEKI IS '変更前児童生徒国籍'
/
COMMENT ON COLUMN GKBWL340R001.MAE_HOGOSYA_KOKUSEKI IS '変更前保護者国籍'
/
COMMENT ON COLUMN GKBWL340R001.MAE_GAKOMEI IS '変更前学校名'
/
COMMENT ON COLUMN GKBWL340R001.MAE_GAKUNEN IS '変更前学年'
/
COMMENT ON COLUMN GKBWL340R001.MAE_JIDOJUSHO IS '変更前児童生徒住所'
/
COMMENT ON COLUMN GKBWL340R001.MAE_NUSHI_SHIMEI_KANJI IS '変更前世帯主氏名'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_TODOKEDE_BI IS '学齢簿変更届出年月日'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_BI IS '学齢簿変更年月日'
/
COMMENT ON COLUMN GKBWL340R001.JIDO_KOKUSEKI IS '変更後児童生徒国籍'
/
COMMENT ON COLUMN GKBWL340R001.HOGOSYA_KOKUSEKI IS '変更後保護者国籍'
/
COMMENT ON COLUMN GKBWL340R001.GAKOMEI IS '変更後学校名'
/
COMMENT ON COLUMN GKBWL340R001.GAKUNEN IS '変更後学年'
/
COMMENT ON COLUMN GKBWL340R001.NUSHI_SHIMEI_KANJI_HENKOUGO IS '変更後世帯主氏名'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_JIYU IS '学齢簿変更事由'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_TODOKEDE_BI_KAISHI IS '変更届出年月日_期間(開始)'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_TODOKEDE_BI_SHURYO IS '変更届出年月日_期間(終了)'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_BI_KAISHI IS '変更年月日_期間(開始)'
/
COMMENT ON COLUMN GKBWL340R001.HENKO_BI_SHURYO IS '変更年月日_期間(終了)'
/
COMMENT ON COLUMN GKBWL340R001.BREAK_NO IS '改ページキー'
/
COMMENT ON COLUMN GKBWL340R001.WSNUM IS '端末番号'
/
COMMENT ON COLUMN GKBWL340R001.BATCHKBN IS '即時バッチ区分'
/
COMMENT ON COLUMN GKBWL340R001.JOBNUM IS 'ジョブNO'
/
CREATE INDEX GKBWL340R001_IDX1
ON GKBWL340R001
(WSNUM, BATCHKBN, JOBNUM, NO)
TABLESPACE GK_INDEX
LOGGING
VISIBLE
/
