CREATE TABLE GKBWL400R002
(
    NO                             NUMBER(38,0),
    SAKUSEI_YMD                    NVARCHAR2(1000),
    TITLE                          NVARCHAR2(1000),
    BUNSHO_NO                      NVARCHAR2(1000),
    HAKKO_YMD                      NVARCHAR2(1000),
    SOFUSAKI_SHIMEI                NVARCHAR2(1000),
    SOFUSAKI_YUBIN_NO              NVARCHAR2(1000),
    SOFUSAKI_JUSHO                 NVARCHAR2(1000),
    JIDO_SHIMEI_KANA               NVARCHAR2(1000),
    JIDO_SHIMEI_KANJI              NVARCHAR2(1000),
    SEINENGAPI                     NVARCHAR2(1000),
    SEIBETSU                       NVARCHAR2(1000),
    JIDO_SHIENSOCHI                NVARCHAR2(1000),
    HOGOSHA_SHIMEI_KANA            NVARCHAR2(1000),
    HOGOSHA_SHIMEI_KANJI           NVARCHAR2(1000),
    HOGOSHA_ZOKUGARA               NVARCHAR2(1000),
    HOGOSHA_SHIENSOCHI             NVARCHAR2(1000),
    GAKKO_MEI                      NVARCHAR2(1000),
    KENSU                          NVARCHAR2(1000),
    GAKKO_CD                       NVARCHAR2(1000),
    JIDO_SHIMEI_LABEL              NVARCHAR2(1000),
    HOGOSHA_SHIMEI_LABEL           NVARCHAR2(1000),
    GAKKO_GYOSEIKU_LABEL           NVARCHAR2(1000),
    BREAK_NO                       NVARCHAR2(1000),
    WSNUM                          NVARCHAR2(63),
    BATCHKBN                       NUMBER(2,0),
    JOBNUM                         NUMBER(38,0)
)
TABLESPACE GK_DATA
NOCACHE
LOGGING
/
COMMENT ON COLUMN GKBWL400R002.NO IS 'ソート順'
/
COMMENT ON COLUMN GKBWL400R002.SAKUSEI_YMD IS '作成年月日'
/
COMMENT ON COLUMN GKBWL400R002.TITLE IS 'タイトル'
/
COMMENT ON COLUMN GKBWL400R002.BUNSHO_NO IS '文書番号'
/
COMMENT ON COLUMN GKBWL400R002.HAKKO_YMD IS '発行年月日'
/
COMMENT ON COLUMN GKBWL400R002.SOFUSAKI_SHIMEI IS '送付先氏名'
/
COMMENT ON COLUMN GKBWL400R002.SOFUSAKI_YUBIN_NO IS '送付先郵便番号'
/
COMMENT ON COLUMN GKBWL400R002.SOFUSAKI_JUSHO IS '送付先住所'
/
COMMENT ON COLUMN GKBWL400R002.JIDO_SHIMEI_KANA IS '児童生徒氏名カナ'
/
COMMENT ON COLUMN GKBWL400R002.JIDO_SHIMEI_KANJI IS '児童生徒氏名漢字'
/
COMMENT ON COLUMN GKBWL400R002.SEINENGAPI IS '生年月日'
/
COMMENT ON COLUMN GKBWL400R002.SEIBETSU IS '性別'
/
COMMENT ON COLUMN GKBWL400R002.JIDO_SHIENSOCHI IS '児童生徒_支援措置'
/
COMMENT ON COLUMN GKBWL400R002.HOGOSHA_SHIMEI_KANA IS '保護者氏名カナ'
/
COMMENT ON COLUMN GKBWL400R002.HOGOSHA_SHIMEI_KANJI IS '保護者氏名漢字'
/
COMMENT ON COLUMN GKBWL400R002.HOGOSHA_ZOKUGARA IS '児童生徒との関係'
/
COMMENT ON COLUMN GKBWL400R002.HOGOSHA_SHIENSOCHI IS '保護者_支援措置'
/
COMMENT ON COLUMN GKBWL400R002.GAKKO_MEI IS '学校名'
/
COMMENT ON COLUMN GKBWL400R002.KENSU IS '件数'
/
COMMENT ON COLUMN GKBWL400R002.GAKKO_CD IS '学校コード'
/
COMMENT ON COLUMN GKBWL400R002.JIDO_SHIMEI_LABEL IS '児童生徒氏名_ラベル'
/
COMMENT ON COLUMN GKBWL400R002.HOGOSHA_SHIMEI_LABEL IS '保護者氏名_ラベル'
/
COMMENT ON COLUMN GKBWL400R002.GAKKO_GYOSEIKU_LABEL IS '学校/行政区_ラベル'
/
COMMENT ON COLUMN GKBWL400R002.BREAK_NO IS '改ページキー'
/
COMMENT ON COLUMN GKBWL400R002.WSNUM IS '端末番号'
/
COMMENT ON COLUMN GKBWL400R002.BATCHKBN IS '即時バッチ区分'
/
COMMENT ON COLUMN GKBWL400R002.JOBNUM IS 'ジョブNO'
/
CREATE INDEX GKBWL400R002_IDX1
ON GKBWL400R002
(WSNUM, BATCHKBN, JOBNUM, NO)
TABLESPACE GK_INDEX
LOGGING
VISIBLE
/
