CREATE TABLE GKBWL290R003
(
    NO                             NUMBER(38,0),
    KAISHI_SEIREKI                 NVARCHAR2(1000),
    SHURYO_SEIREKI                 NVARCHAR2(1000),
    GAKKO_MEI                      NVARCHAR2(1000),
    SAKUSEIBI                      NVARCHAR2(1000),
    OLD_SHIMEI_KANA                NVARCHAR2(1000),
    OLD_SHIMEI_KANJI               NVARCHAR2(1000),
    OLD_CHOMEI                     NVARCHAR2(1000),
    OLD_BANCHI                     NVARCHAR2(1000),
    OLD_KATAGAKI                   NVARCHAR2(1000),
    OLD_HOGOSHA_TSUDUKIGARA        NVARCHAR2(1000),
    OLD_GAKKO                      NVARCHAR2(1000),
    OLD_HOGOSHA_SHIMEI_KANA        NVARCHAR2(1000),
    OLD_HOGOSHA_SHIMEI_KANJI       NVARCHAR2(1000),
    OLD_HOGOSHA_CHOMEI             NVARCHAR2(1000),
    OLD_HOGOSHA_BANCHI             NVARCHAR2(1000),
    OLD_HOGOSHA_KATAGAKI           NVARCHAR2(1000),
    NEW_JIDO_SHIMEI_KANA           NVARCHAR2(1000),
    NEW_JIDO_SHIMEI_KANJI          NVARCHAR2(1000),
    NEW_CHOMEI                     NVARCHAR2(1000),
    NEW_BANCHI                     NVARCHAR2(1000),
    NEW_KATAGAKI                   NVARCHAR2(1000),
    NEW_HOGOSHA_TSUDUKIGARA        NVARCHAR2(1000),
    NEW_GAKKO                      NVARCHAR2(1000),
    NEW_HOGOSHA_SHIMEI_KANA        NVARCHAR2(1000),
    NEW_HOGOSHA_SHIMEI_KANJI       NVARCHAR2(1000),
    NEW_HOGOSHA_CHOMEI             NVARCHAR2(1000),
    NEW_HOGOSHA_BANCHI             NVARCHAR2(1000),
    NEW_HOGOSHA_KATAGAKI           NVARCHAR2(1000),
    JIDO_KOJIN_NO                  NVARCHAR2(1000),
    SEINENGAPI                     NVARCHAR2(1000),
    SEIBETSU                       NVARCHAR2(1000),
    GAKUNEN                        NVARCHAR2(1000),
    SETAI_NO                       NVARCHAR2(1000),
    HOGOSHA_KOJIN_NO               NVARCHAR2(1000),
    IDO_BI                         NVARCHAR2(1000),
    TODOKEDEBI                     NVARCHAR2(1000),
    IDO_JIYU                       NVARCHAR2(1000),
    BIKO                           NVARCHAR2(1000),
    JINKAKU_KBN                    NVARCHAR2(1000),
    BREAK_NO                       NVARCHAR2(1000),
    WSNUM                          NVARCHAR2(63),
    BATCHKBN                       NUMBER(2,0),
    JOBNUM                         NUMBER(38,0)
)
TABLESPACE GK_DATA
NOCACHE
LOGGING
/
COMMENT ON TABLE GKBWL290R003 IS '変更通知リストワーク'
/
COMMENT ON COLUMN GKBWL290R003.NO IS 'ソート順'
/
COMMENT ON COLUMN GKBWL290R003.KAISHI_SEIREKI IS '異動開始日'
/
COMMENT ON COLUMN GKBWL290R003.SHURYO_SEIREKI IS '異動終了日'
/
COMMENT ON COLUMN GKBWL290R003.GAKKO_MEI IS '学校名'
/
COMMENT ON COLUMN GKBWL290R003.SAKUSEIBI IS '作成年月日'
/
COMMENT ON COLUMN GKBWL290R003.OLD_SHIMEI_KANA IS '旧児童氏名かな'
/
COMMENT ON COLUMN GKBWL290R003.OLD_SHIMEI_KANJI IS '旧児童氏名漢字'
/
COMMENT ON COLUMN GKBWL290R003.OLD_CHOMEI IS '旧児童生徒－町名'
/
COMMENT ON COLUMN GKBWL290R003.OLD_BANCHI IS '旧児童生徒－地番'
/
COMMENT ON COLUMN GKBWL290R003.OLD_KATAGAKI IS '旧児童生徒－方書'
/
COMMENT ON COLUMN GKBWL290R003.OLD_HOGOSHA_TSUDUKIGARA IS '旧保護者との続柄'
/
COMMENT ON COLUMN GKBWL290R003.OLD_GAKKO IS '旧学校'
/
COMMENT ON COLUMN GKBWL290R003.OLD_HOGOSHA_SHIMEI_KANA IS '旧保護者氏名かな'
/
COMMENT ON COLUMN GKBWL290R003.OLD_HOGOSHA_SHIMEI_KANJI IS '旧保護者氏名漢字'
/
COMMENT ON COLUMN GKBWL290R003.OLD_HOGOSHA_CHOMEI IS '旧保護者－町名'
/
COMMENT ON COLUMN GKBWL290R003.OLD_HOGOSHA_BANCHI IS '旧保護者－地番'
/
COMMENT ON COLUMN GKBWL290R003.OLD_HOGOSHA_KATAGAKI IS '旧保護者－方書'
/
COMMENT ON COLUMN GKBWL290R003.NEW_JIDO_SHIMEI_KANA IS '新児童氏名かな'
/
COMMENT ON COLUMN GKBWL290R003.NEW_JIDO_SHIMEI_KANJI IS '新児童氏名漢字'
/
COMMENT ON COLUMN GKBWL290R003.NEW_CHOMEI IS '新児童生徒－町名'
/
COMMENT ON COLUMN GKBWL290R003.NEW_BANCHI IS '新児童生徒－地番'
/
COMMENT ON COLUMN GKBWL290R003.NEW_KATAGAKI IS '新児童生徒－方書'
/
COMMENT ON COLUMN GKBWL290R003.NEW_HOGOSHA_TSUDUKIGARA IS '新保護者との続柄'
/
COMMENT ON COLUMN GKBWL290R003.NEW_GAKKO IS '新学校'
/
COMMENT ON COLUMN GKBWL290R003.NEW_HOGOSHA_SHIMEI_KANA IS '新保護者氏名かな'
/
COMMENT ON COLUMN GKBWL290R003.NEW_HOGOSHA_SHIMEI_KANJI IS '新保護者氏名漢字'
/
COMMENT ON COLUMN GKBWL290R003.NEW_HOGOSHA_CHOMEI IS '新保護者－町名'
/
COMMENT ON COLUMN GKBWL290R003.NEW_HOGOSHA_BANCHI IS '新保護者－地番'
/
COMMENT ON COLUMN GKBWL290R003.NEW_HOGOSHA_KATAGAKI IS '新保護者－方書'
/
COMMENT ON COLUMN GKBWL290R003.JIDO_KOJIN_NO IS '児童個人番号'
/
COMMENT ON COLUMN GKBWL290R003.SEINENGAPI IS '生年月日'
/
COMMENT ON COLUMN GKBWL290R003.SEIBETSU IS '性別'
/
COMMENT ON COLUMN GKBWL290R003.GAKUNEN IS '学年'
/
COMMENT ON COLUMN GKBWL290R003.SETAI_NO IS '世帯番号'
/
COMMENT ON COLUMN GKBWL290R003.HOGOSHA_KOJIN_NO IS '保護者個人番号'
/
COMMENT ON COLUMN GKBWL290R003.IDO_BI IS '異動日'
/
COMMENT ON COLUMN GKBWL290R003.TODOKEDEBI IS '届出日'
/
COMMENT ON COLUMN GKBWL290R003.IDO_JIYU IS '異動事由'
/
COMMENT ON COLUMN GKBWL290R003.BIKO IS '備考'
/
COMMENT ON COLUMN GKBWL290R003.JINKAKU_KBN IS '人格区分'
/
COMMENT ON COLUMN GKBWL290R003.BREAK_NO IS '改ページキー'
/
COMMENT ON COLUMN GKBWL290R003.WSNUM IS '端末番号'
/
COMMENT ON COLUMN GKBWL290R003.BATCHKBN IS '即時バッチ区分'
/
COMMENT ON COLUMN GKBWL290R003.JOBNUM IS 'ジョブNO'
/
CREATE INDEX GKBWL290R003_IDX1
ON GKBWL290R003
(WSNUM, BATCHKBN, JOBNUM, NO)
TABLESPACE GK_INDEX
LOGGING
VISIBLE
/
