CREATE TABLE GKBWRGAKUKYUSETTEI
(
    ROWNUMBER                      NUMBER(9,0)  NOT NULL,
    DATA                           BLOB,
    FILEID                         NVARCHAR2(255),
    FILENAME                       NVARCHAR2(255) NOT NULL,
    FILESIZE                       NUMBER(15,0),
    FILEUPDATETIME                 CHAR(23),
    RECUPDTANTOCODE                CHAR(12),
    RECUPDDATETIME                 CHAR(23),
    RECUPDWSNUM                    NVARCHAR2(63),
    RECUPDKBNCODE                  CHAR(2)
)
TABLESPACE GK_DATA
NOCACHE
LOGGING
/
COMMENT ON TABLE GKBWRGAKUKYUSETTEI IS 'アップロード用累積テーブル（GKBWRGAKUKYUSETTEI）'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.ROWNUMBER IS 'ファイル内連番（必須）'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.DATA IS 'BLOBロケータ'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.FILEID IS 'ファイルID（任意）'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.FILENAME IS 'ファイル名（必須）'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.FILESIZE IS 'ファイルサイズ'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.FILEUPDATETIME IS 'ファイル更新日'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.RECUPDTANTOCODE IS '更新担当者コード'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.RECUPDDATETIME IS '更新日時'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.RECUPDWSNUM IS '更新端末番号'
/
COMMENT ON COLUMN GKBWRGAKUKYUSETTEI.RECUPDKBNCODE IS '更新処理区分コード'
/
