CREATE TABLE GKBWHANYOERRLIST
(
    SUB_TITLE                      NVARCHAR2(30),
    MIDASHI1                       NVARCHAR2(30),
    MIDASHI2                       NVARCHAR2(30),
    MIDASHI3                       NVARCHAR2(30),
    SHORIBI                        NUMBER(8,0) DEFAULT 0,
    HENSHU_SHORIBI                 NVARCHAR2(11),
    NUM                            NUMBER(5,0) DEFAULT 0,
    ERR_NAIYO                      NVARCHAR2(500),
    SAKUSEIBI                      NUMBER(8,0) DEFAULT 0,
    SYS_KOSHINBI                   NUMBER(8,0) DEFAULT 0,
    SYS_JIKAN                      NUMBER(6,0) DEFAULT 0,
    SYS_SHOKUINKOJIN_NO            CHAR(12),
    SYS_TANMATSU_NO                NVARCHAR2(63)
)
TABLESPACE GK_DATA
NOCACHE
LOGGING
/
COMMENT ON TABLE GKBWHANYOERRLIST IS '汎用エラーリストワーク'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SUB_TITLE IS 'サブタイトル'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.MIDASHI1 IS '見出し１'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.MIDASHI2 IS '見出し２'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.MIDASHI3 IS '見出し３'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SHORIBI IS '処理日'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.HENSHU_SHORIBI IS '処理日選択項目'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.NUM IS 'Ｎｏ'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.ERR_NAIYO IS 'エラー内容'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SAKUSEIBI IS '作成日'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SYS_KOSHINBI IS '更新日'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SYS_JIKAN IS '更新時間'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SYS_SHOKUINKOJIN_NO IS '更新職員宛名番号'
/
COMMENT ON COLUMN GKBWHANYOERRLIST.SYS_TANMATSU_NO IS '更新端末番号'
/
