CREATE TABLE GKBWL240R002
(
    NO                             NUMBER(38,0),
    KAIPAGE_CD                     NVARCHAR2(1000),
    KAIPAGE_MEI                    NVARCHAR2(1000),
    RENBAN                         NVARCHAR2(1000),
    GAKKO_MEI                      NVARCHAR2(1000),
    GAKKO_CD                       NVARCHAR2(1000),
    SAKUSEIBI                      NVARCHAR2(1000),
    GYOSEIKU                       NVARCHAR2(1000),
    JIDO_SHIMEI_JODAN              NVARCHAR2(1000),
    JIDO_SHIMEI_GEDAN              NVARCHAR2(1000),
    JIDO_KOJIN_NO                  NVARCHAR2(1000),
    HYOJI_SEINENGAPI               NVARCHAR2(1000),
    SEIBETSU                       NVARCHAR2(1000),
    JIDO_CHOMEI_BANCHI_KATAGAKI    NVARCHAR2(1000),
    JIDO_YUBIN_NO                  NVARCHAR2(1000),
    HOGOSHA_SHIMEI_JODAN           NVARCHAR2(1000),
    HOGOSHA_SHIMEI_GEDAN           NVARCHAR2(1000),
    HOGOSHA_ZOKUGARAMEI            NVARCHAR2(1000),
    JIDO_ZOKUGARAMEI               NVARCHAR2(1000),
    HOGOSHA_JUSHO                  NVARCHAR2(1000),
    HOGOSHA_YUBIN_NO               NVARCHAR2(1000),
    HOGOSHA_JUSHO_JODAN            NVARCHAR2(1000),
    HOGOSHA_JUSHO_GEDAN            NVARCHAR2(1000),
    KIJUNBI                        NVARCHAR2(1000),
    KAISHIBI                       NVARCHAR2(1000),
    SHURYOBI                       NVARCHAR2(1000),
    JINKAKU_KBN                    NVARCHAR2(1000),
    BREAK_NO                       NVARCHAR2(1000),
    WSNUM                          NVARCHAR2(63),
    BATCHKBN                       NUMBER(2,0),
    JOBNUM                         NUMBER(38,0)
)
TABLESPACE GK_DATA
NOCACHE
LOGGING
/
COMMENT ON TABLE GKBWL240R002 IS '宛名ラベル（住基参照）発送者一覧表ワーク'
/
COMMENT ON COLUMN GKBWL240R002.NO IS 'ソート順'
/
COMMENT ON COLUMN GKBWL240R002.KAIPAGE_CD IS '改頁コード'
/
COMMENT ON COLUMN GKBWL240R002.KAIPAGE_MEI IS '改頁名'
/
COMMENT ON COLUMN GKBWL240R002.RENBAN IS '連番'
/
COMMENT ON COLUMN GKBWL240R002.GAKKO_MEI IS '学校名'
/
COMMENT ON COLUMN GKBWL240R002.GAKKO_CD IS '学校コード'
/
COMMENT ON COLUMN GKBWL240R002.SAKUSEIBI IS '作成日'
/
COMMENT ON COLUMN GKBWL240R002.GYOSEIKU IS '行政区'
/
COMMENT ON COLUMN GKBWL240R002.JIDO_SHIMEI_JODAN IS '児童氏名上段'
/
COMMENT ON COLUMN GKBWL240R002.JIDO_SHIMEI_GEDAN IS '児童氏名下段'
/
COMMENT ON COLUMN GKBWL240R002.JIDO_KOJIN_NO IS '児童個人番号'
/
COMMENT ON COLUMN GKBWL240R002.HYOJI_SEINENGAPI IS '表示生年月日'
/
COMMENT ON COLUMN GKBWL240R002.SEIBETSU IS '性別'
/
COMMENT ON COLUMN GKBWL240R002.JIDO_CHOMEI_BANCHI_KATAGAKI IS '児童町名番地方書'
/
COMMENT ON COLUMN GKBWL240R002.JIDO_YUBIN_NO IS '児童郵便番号'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_SHIMEI_JODAN IS '保護者氏名上段'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_SHIMEI_GEDAN IS '保護者氏名下段'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_ZOKUGARAMEI IS '保護者続柄名'
/
COMMENT ON COLUMN GKBWL240R002.JIDO_ZOKUGARAMEI IS '児童続柄名'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_JUSHO IS '保護者町名番地方書'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_YUBIN_NO IS '保護者郵便番号'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_JUSHO_JODAN IS '保護者住所上段'
/
COMMENT ON COLUMN GKBWL240R002.HOGOSHA_JUSHO_GEDAN IS '保護者住所下段'
/
COMMENT ON COLUMN GKBWL240R002.KIJUNBI IS '基準日'
/
COMMENT ON COLUMN GKBWL240R002.KAISHIBI IS '条件抽出開始日'
/
COMMENT ON COLUMN GKBWL240R002.SHURYOBI IS '条件抽出終了日'
/
COMMENT ON COLUMN GKBWL240R002.JINKAKU_KBN IS '人格区分'
/
COMMENT ON COLUMN GKBWL240R002.BREAK_NO IS '改ページキー'
/
COMMENT ON COLUMN GKBWL240R002.WSNUM IS '端末番号'
/
COMMENT ON COLUMN GKBWL240R002.BATCHKBN IS '即時バッチ区分'
/
COMMENT ON COLUMN GKBWL240R002.JOBNUM IS 'ジョブNO'
/
CREATE INDEX GKBWL240R002_IDX1
ON GKBWL240R002
(WSNUM, BATCHKBN, JOBNUM, NO)
TABLESPACE GK_INDEX
LOGGING
VISIBLE
/
