@ECHO OFF
REM このSQLは各業務別の「01.SQL」ディレクトリの直下に配置してください。
REM ----------------
SET WIZ_GYOUMU=GKB
REM ----------------
REM 以下のコマンドは、全業務共通です。

ECHO %WIZ_GYOUMU%業務のデータベース資産を一括して登録します

REM ------共通環境変数のセット
CALL ../../../../00_Wiz/DB/01.SQL/SETENVS.BAT
ECHO この処理を実行すると、%WIZ_GYOUMU%業務データがすべて失われます。
PAUSE

REM 作業用SQLの生成
ECHO SPOOL %WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_ETC.log APPEND>$TEMP.SQL
ECHO SELECT TO_CHAR(SYSTIMESTAMP, 'YYYY/MM/DD HH24:MI:SS:FF3') 現在時刻 FROM DUAL; >>$TEMP.SQL
ECHO SET DEFINE OFF >>$TEMP.SQL

ECHO TABLEの登録
FOR %%S IN (TABLE\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO SEQUENCEの登録
FOR %%S IN (SEQUENCE\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO TYPEの登録
FOR %%S IN (TYPE\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO VIEWの登録
FOR %%S IN (VIEW\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO SYNONYMの登録
FOR %%S IN (SYNONYM\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO FUNCTIONの登録
FOR %%S IN (FUNCTION\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO PROCEDUREの登録
FOR %%S IN (PROCEDURE\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO PACKAGEの登録
FOR %%S IN (PACKAGE\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO PACKAGE_BODYの登録
FOR %%S IN (PACKAGE_BODY\*.SQL) DO ECHO @%%S >>$TEMP.SQL

ECHO COMMIT; >>$TEMP.SQL
ECHO SELECT TO_CHAR(SYSTIMESTAMP, 'YYYY/MM/DD HH24:MI:SS:FF3') 現在時刻 FROM DUAL; >>$TEMP.SQL
ECHO EXIT >>$TEMP.SQL

DEL %WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_ETC.log
ECHO %WIZ_GYOUMU% データベース資産の登録
ECHO %WIZ_GYOUMU% データベース資産の登録 > %WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_ETC.log
%WIZ_PLUS_NAME% %WIZ_DB_USER%/%WIZ_DB_PASS%@%WIZ_DB_CONNECT% @$TEMP.SQL

DEL $TEMP.SQL
ECHO %WIZ_GYOUMU% 処理結果は、%WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_ETC.log に出力されています。
PAUSE 
EXIT