@ECHO OFF
REM このSQLは各業務別の「01.SQL」ディレクトリの直下に配置してください。
REM ----------------
SET WIZ_GYOUMU=GKB
REM ----------------
REM 以下のコマンドは、全業務共通です。

ECHO %WIZ_GYOUMU%業務のデータベース資産(テーブルのみ)を一括して登録します
cd %~dp0
REM ------共通環境変数のセット
CALL ../../../../00_Wiz/DB/01.SQL/SETENVS.bat
REM PAUSE


REM 作業用SQLの生成
ECHO SPOOL %WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_TABLE.log APPEND>%WIZ_LOGPATH%\TEMP.SQL
ECHO SELECT TO_CHAR(SYSTIMESTAMP, 'YYYY/MM/DD HH24:MI:SS:FF3') 現在時刻 FROM DUAL; >>%WIZ_LOGPATH%\TEMP.SQL
ECHO SET DEFINE OFF >>%WIZ_LOGPATH%\TEMP.SQL

ECHO TABLEの登録
FOR %%S IN (TABLE\*.SQL) DO ECHO @%%S >>%WIZ_LOGPATH%\TEMP.SQL

ECHO COMMIT; >>%WIZ_LOGPATH%\TEMP.SQL
ECHO SELECT TO_CHAR(SYSTIMESTAMP, 'YYYY/MM/DD HH24:MI:SS:FF3') 現在時刻 FROM DUAL; >>%WIZ_LOGPATH%\TEMP.SQL
ECHO EXIT >>%WIZ_LOGPATH%\TEMP.SQL

DEL %WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_TABLE.log
ECHO %WIZ_GYOUMU% データベース資産(テーブルのみ)の登録
ECHO %WIZ_GYOUMU% データベース資産(テーブルのみ)の登録 > %WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_TABLE.log
%WIZ_PLUS_NAME% %WIZ_DB_USER%/%WIZ_DB_PASS%@%WIZ_DB_CONNECT% @%WIZ_LOGPATH%\TEMP.SQL

DEL %WIZ_LOGPATH%\TEMP.SQL
ECHO %WIZ_GYOUMU% 処理結果は、%WIZ_LOGPATH%\%WIZ_GYOUMU%_CREATE_TABLE.log に出力されています。
REM PAUSE 